# ----------------------------------------------------- 
# Autostart
# ----------------------------------------------------- 

exec-once = swaybg -i /home/amit/Pictures/black_bmw.jpeg -m fill
exec-once = ~/.config/hypr/autostart.sh
exec-once = hyprlock
