# ----------------------------------------------------- 
# Autostart
# ----------------------------------------------------- 

exec-once = hyprpaper
exec-once = ~/.config/hypr/autostart.sh
exec-once = hyprlock
