# ----------------------------------------------------- 
# Input Devices
# ----------------------------------------------------- 

input {
    kb_layout = us
    follow_mouse = 1
    # Ensure focus behavior is robust for dialogs
    mouse_refocus = true
    float_switch_override_focus = 0
    
    accel_profile = flat
    touchpad {
        natural_scroll = true
    }
}
