# ----------------------------------------------------- 
# Window Rules
# ----------------------------------------------------- 

# Floating rules for specific apps
windowrule = match:class ^(pavucontrol|dialog|confirm|error|notification|splash|xdg-desktop-portal-gtk)$, float on
windowrule = match:class ^(pavucontrol|dialog|confirm|error|notification|splash|xdg-desktop-portal-gtk)$, center on

windowrule = match:class ^(?i)(mpv|feh|pqiv|sxiv|pavucontrol|blueman-manager)$, float on
windowrule = match:class ^(?i)(mpv|feh|pqiv|sxiv)$, center on
windowrule = match:class ^(?i)(.*dialog.*)$, float on
windowrule = match:class ^(?i)(.*dialog.*)$, center on

# ----------------------------------------------------- 
# Default Global Rule
# ----------------------------------------------------- 
windowrule = match:class .*, tile on

# ----------------------------------------------------- 
# Floating Workspaces (7, 8, 9)
# ----------------------------------------------------- 
windowrule = match:workspace 7, float on
windowrule = match:workspace 8, float on
windowrule = match:workspace 9, float on
