# ----------------------------------------------------- 
# Workspace Defaults
# ----------------------------------------------------- 

workspace = 1, default_floating:false
workspace = 2, default_floating:false
workspace = 3, default_floating:false
workspace = 4, default_floating:false
workspace = 5, default_floating:false
workspace = 6, default_floating:false

workspace = 7, default_floating:true
workspace = 8, default_floating:true
workspace = 9, default_floating:true
