# Font
font_family      monospace
font_size        12.5

# Colors
background       #000000
background_opacity 0.88
foreground       #dcdcdc
selection_background #546a5a
selection_foreground #ffffff
# cursor           #ffffff
cursor #c0c0c0
cursor_text_color #000000
bold_brightens_foreground yes

color0  #000000
color1  #ff2b2b
color2  #00ff6a
color3  #ffdf00
color4  #2f80ff
color5  #ff00d8
color6  #00eaff
color7  #ededed
color8  #7a7a7a
color9  #ff5c5c
color10 #7dff9f
color11 #fff37a
color12 #8ab4ff
color13 #ff7df3
color14 #7cf7ff
color15 #ffffff

detect_urls yes
url_color #00f5ff
url_style underline

# Cursor
cursor_shape     beam
cursor_blink_interval 0.5

# Window
window_padding_width 8

# Scrollback
scrollback_lines 10000

# Performance
repaint_delay    8
input_delay      1
sync_to_monitor  yes

# Keybinds
kitty_mod        ctrl+shift
map ctrl+equal   change_font_size current +2
map ctrl+minus   change_font_size current -2
map ctrl+0       change_font_size current 0