# ----------------------------------------------------- 
# Desktop Visuals & Animations
# ----------------------------------------------------- 

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 2         
    col.active_border = rgba(3399ffee)
    col.inactive_border = rgba(595959aa)
    resize_on_border = true
    layout = dwindle
}

decoration {
    rounding = 6
    shadow {
        enabled = false
    }
    blur {
        enabled = true
        size = 6
        passes = 3
    }
}

animations {
    enabled = yes
    animation = windows, 1, 4, default
    animation = windowsOut, 1, 4, default
    animation = fade, 1, 5, default
    animation = fadeDim, 1, 5, default
}

misc {
    disable_autoreload = false
    force_default_wallpaper = 0
}
