# ----------------------------------------------------- 
# General Layout Settings
# ----------------------------------------------------- 
general {
    gaps_in = 0             # Gaps between windows
    gaps_out = 0            # Gaps between windows and monitor edges
    border_size = 1         # Width of the window border
    resize_on_border = true # Allow resizing by dragging borders
    layout = dwindle        # Use dwindle layout
}

# ----------------------------------------------------- 
# Window Rules (Floating vs Tiling)
# ----------------------------------------------------- 
windowrule = center on, match:class ^(dialog|pavucontrol)$ # Center dialogs and audio control
windowrule = tile on, match:class .*                       # Default all windows to tile
windowrule = tile on, match:class ^(thunar|Thunar)$        # Ensure file manager tiles


# ----------------------------------------------------- 
# Window Decorations
# ----------------------------------------------------- 
decoration {
    rounding = 6            # Rounded corners radius
    shadow {
        enabled = false     # Disable window shadows
    }
}

# ----------------------------------------------------- 
# Input Configuration
# ----------------------------------------------------- 
input {
    kb_layout = us          # Keyboard layout
    follow_mouse = 1        # Focus follows mouse movement
    accel_profile = flat    # Flat acceleration profile
    touchpad {
        natural_scroll = true # Natural scrolling for touchpad
    }
}

# ----------------------------------------------------- 
# Mouse Bindings for Window Management
# ----------------------------------------------------- 
bindm = SUPER, mouse:272, movewindow   # Move window with Left Mouse Button
bindm = SUPER, mouse:273, resizewindow # Resize window with Right Mouse Button

# ----------------------------------------------------- 
# Miscellaneous Settings
# ----------------------------------------------------- 
misc {
    disable_autoreload = false   # Auto-reload config on save
    force_default_wallpaper = 0  # Disable default wallpaper
}