windowrulev2 = float, ^(?i)(mpv|feh|pqiv|sxiv|pavucontrol|blueman-manager)$
windowrulev2 = center, ^(?i)(mpv|feh|pqiv|sxiv)$
windowrulev2 = float, ^(?i)(.*dialog.*)$
windowrulev2 = center, ^(?i)(.*dialog.*)$
