source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/theme.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/floating.conf
source = ~/.config/hypr/extra.conf
exec-once = swaybg -i /home/amit/Pictures/black_bmw.jpeg -m fill
