# ----------------------------------------------------- 
# HYPRLAND CONFIGURATION FILE
# ----------------------------------------------------- 
# Welcome to your freshly organized Hyprland dotfiles!
# Every configuration is beautifully divided into the conf/ directory.

source = ~/.config/hypr/conf/environment.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/keyboard.conf
source = ~/.config/hypr/conf/customization.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/workspaces.conf
source = ~/.config/hypr/conf/keybinding.conf
source = ~/.config/hypr/conf/autostart.conf
