preload = /home/amit/.config/hypr/spiderman.jpeg

wallpaper {
    monitor = eDP-1
    path = /home/amit/.config/hypr/spiderman.jpeg
}

wallpaper {
    monitor =
    path = /home/amit/.config/hypr/spiderman.jpeg
}
