splash = false
ipc = on

wallpaper {
	monitor = eDP-1
	path = /home/amit/Pictures/prime2.png
	fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-1
	path = /home/amit/Pictures/prime2.png
	fit_mode = cover
}

wallpaper {
	monitor = 
	path = /home/amit/Pictures/prime2.png
	fit_mode = cover
}
