# ----------------------------------------------------- 
# HYPRLAND CONFIGURATION FILE
# ----------------------------------------------------- 
# Welcome to your freshly organized Hyprland dotfiles!
# Every configuration is beautifully divided into the conf/ directory.

source = ~/.config/hypr/conf/environment.conf
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/keyboard.conf
source = ~/.config/hypr/conf/customization.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/workspaces.conf
source = ~/.config/hypr/conf/keybinding.conf
source = ~/.config/hypr/conf/autostart.conf
env = GTK_THEME,Adwaita:dark
env = QT_QPA_PLATFORMTHEME,qt5ct
exec-once = xsettingsd
env = GTK_ICON_THEME,Papirus-Dark
env = GTK_APPLICATION_PREFER_DARK_THEME,1
