# ----------------------------------------------------- 
# Environment Variables
# ----------------------------------------------------- 
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland

# ----------------------------------------------------- 
# Application Shortcuts
# ----------------------------------------------------- 
bind = SUPER, E, exec, thunar # Open file manager
bind = SUPER, RETURN, exec, kitty --config ~/.config/kitty/kitty.conf # Open terminal
bind = SUPER, D, exec, rofi -show drun -theme ~/.config/rofi/simple.rasi # Open application launcher
bind = SUPER, W, exec, pgrep waybar >/dev/null && pkill waybar || waybar & # Toggle Waybar

# ----------------------------------------------------- 
# System Controls
# ----------------------------------------------------- 
bind = SUPER, N, exec, bash -c 'pgrep hyprsunset && pkill hyprsunset || hyprsunset --temperature 4500' # Toggle blue light filter
bind = SUPER, S, exec, ~/.config/hypr/scripts/named_screenshot.sh # Take a screenshot
bind = SUPER, R, exec, hyprctl reload # Reload Hyprland configuration

# ----------------------------------------------------- 
# Window Focus & Movement
# ----------------------------------------------------- 
bind = SUPER, H, movefocus, l # Move focus left
bind = SUPER, L, movefocus, r # Move focus right
bind = SUPER, J, movefocus, d # Move focus down
bind = SUPER, K, movefocus, u # Move focus up

# ----------------------------------------------------- 
# Window Management
# ----------------------------------------------------- 
bind = SUPER, Q, killactive # Close active window
bind = SUPER, F, togglefloating # Toggle floating mode for window
bind = SUPER, SPACE, fullscreen, 1 # Toggle maximization
bindm = SUPER, mouse:272, movewindow # Move window with mouse
bindm = SUPER, mouse:273, resizewindow # Resize window with mouse

# ----------------------------------------------------- 
# Workspace Management
# ----------------------------------------------------- 
bind = SUPER, 1, workspace, 1 # Switch to workspace 1
bind = SUPER, 2, workspace, 2 # Switch to workspace 2
bind = SUPER, 3, workspace, 3 # Switch to workspace 3
bind = SUPER, 4, workspace, 4 # Switch to workspace 4

# ----------------------------------------------------- 
# Hardware Keys (Volume & Brightness)
# ----------------------------------------------------- 
bind = , XF86MonBrightnessUp, exec, brightnessctl --min-value=50 set +200 # Increase brightness
bind = , XF86MonBrightnessDown, exec, brightnessctl --min-value=50 set 200- # Decrease brightness
bind = , XF86AudioRaiseVolume, exec, pamixer -i 5 # Increase volume
bind = , XF86AudioLowerVolume, exec, pamixer -d 5 # Decrease volume
bind = , XF86AudioMute, exec, pamixer -t # Mute audio
