general {
    col.active_border = rgba(3399ffee)
    col.inactive_border = rgba(595959aa)
    border_size = 3
}
decoration {
    blur {
        enabled = true
        size = 6
        passes = 3
        new_optimizations = true
    }
}
exec-once = hyprpaper
env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
